### ISSUE TITLE
I have a question about the prev_sample calculation process of the MyDDIMScheduler class.

### ISSUE THREAD

**Issue by sangh0Kim** [garibida/ReNoise-Inversion#8]
Congratulations on paper being accepted for ECCV 2024! Very nice work, as expected.

I'd like to ask you a question because there is a part of the code that I don't understand.
In the ddim_scheduler.py file #135, I don't understand this part that used another formula instead of #133, which is the formula for calculating the prev_sample of a typical DDIM scheduler. Can you tell me what the source paper of this formula? I wonder why you changed the calculation like this.

Thank you! :)

**Comment by garibida** [comment]
Hi,

You can see the explanation of this formula in the "Reversing the Sampler" section of our paper. This formula was introduced in "Diffusion Models Beat GANs on Image Synthesis" Appendix Chapter F (page 22).
